version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/myapp
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4000:4000"
    depends_on:
      - database
